// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZM3DlTENDVan-VBQYnZZZsSHK7ruxe18',
    appId: '1:781400144376:web:09b455d04c8fa1a1ef7e0d',
    messagingSenderId: '781400144376',
    projectId: 'gmdapp-2fc8a',
    authDomain: 'gmdapp-2fc8a.firebaseapp.com',
    storageBucket: 'gmdapp-2fc8a.appspot.com',
    measurementId: 'G-NBM2HBW699',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrSmSW7yMeQBS5ZKE59oSaKsAMlxM7jCE',
    appId: '1:781400144376:android:0f9f959265cefa1bef7e0d',
    messagingSenderId: '781400144376',
    projectId: 'gmdapp-2fc8a',
    storageBucket: 'gmdapp-2fc8a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlURzgtJu3ccxHHDTG5Rqi1wanjjUWag8',
    appId: '1:781400144376:ios:7dc6bb9db14220cbef7e0d',
    messagingSenderId: '781400144376',
    projectId: 'gmdapp-2fc8a',
    storageBucket: 'gmdapp-2fc8a.appspot.com',
    iosBundleId: 'com.example.gmdApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAlURzgtJu3ccxHHDTG5Rqi1wanjjUWag8',
    appId: '1:781400144376:ios:7dc6bb9db14220cbef7e0d',
    messagingSenderId: '781400144376',
    projectId: 'gmdapp-2fc8a',
    storageBucket: 'gmdapp-2fc8a.appspot.com',
    iosBundleId: 'com.example.gmdApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDZM3DlTENDVan-VBQYnZZZsSHK7ruxe18',
    appId: '1:781400144376:web:d0c17ff9ba5c462eef7e0d',
    messagingSenderId: '781400144376',
    projectId: 'gmdapp-2fc8a',
    authDomain: 'gmdapp-2fc8a.firebaseapp.com',
    storageBucket: 'gmdapp-2fc8a.appspot.com',
    measurementId: 'G-HBTL5XXKKC',
  );

}